libft Tests: unity/src/unity.c File Reference
unity.c File Reference
#include "unity.h"
#include <stddef.h>
Macros
#define PROGMEM
#define UNITY_FAIL_AND_BAIL { Unity.CurrentTestFailed = 1; UNITY_OUTPUT_FLUSH(); TEST_ABORT(); }
#define UNITY_IGNORE_AND_BAIL { Unity.CurrentTestIgnored = 1; UNITY_OUTPUT_FLUSH(); TEST_ABORT(); }
#define RETURN_IF_FAIL_OR_IGNORE if (Unity.CurrentTestFailed || Unity.CurrentTestIgnored) TEST_ABORT()
#define UnityPrintPointlessAndBail()
#define UNITY_FLOAT_OR_DOUBLE_WITHIN(delta, expected, actual, diff)
#define UNITY_NAN_CHECK isnan(expected) && isnan(actual)
#define UNITY_PRINT_EXPECTED_AND_ACTUAL_FLOAT(expected, actual)
Functions
static void UnityPrintChar (const char *pch)
void UnityPrint (const char *string)
void UnityPrintLen (const char *string, const UNITY_UINT32 length)
void UnityPrintNumberByStyle (const UNITY_INT number, const UNITY_DISPLAY_STYLE_T style)
void UnityPrintNumber (const UNITY_INT number_to_print)
void UnityPrintNumberUnsigned (const UNITY_UINT number)
void UnityPrintNumberHex (const UNITY_UINT number, const char nibbles_to_print)
void UnityPrintMask (const UNITY_UINT mask, const UNITY_UINT number)
void UnityPrintFloat (const UNITY_DOUBLE input_number)
static void UnityTestResultsBegin (const char *file, const UNITY_UINT line)
static void UnityTestResultsFailBegin (const UNITY_UINT line)
void UnityConcludeTest (void)
static void UnityAddMsgIfSpecified (const char *msg)
static void UnityPrintExpectedAndActualStrings (const char *expected, const char *actual)
static void UnityPrintExpectedAndActualStringsLen (const char *expected, const char *actual, const UNITY_UINT32 length)
static int UnityIsOneArrayNull (const void *expected, const void *actual, const UNITY_UINT lineNumber, const char *msg)
void UnityAssertBits (const UNITY_INT mask, const UNITY_INT expected, const UNITY_INT actual, const char *msg, const UNITY_UINT lineNumber)
void UnityAssertEqualNumber (const UNITY_INT expected, const UNITY_INT actual, const char *msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style)
void UnityAssertGreaterOrLessOrEqualNumber (const UNITY_INT threshold, const UNITY_INT actual, const UNITY_COMPARISON_T compare, const char *msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style)
void UnityAssertEqualIntArray (const void *expected, const void *actual, const UNITY_UINT32 num_elements, const char *msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style, const UNITY_FLAGS_T flags)
static int UnityFloatsWithin (UNITY_FLOAT delta, UNITY_FLOAT expected, UNITY_FLOAT actual)
void UnityAssertEqualFloatArray (const UNITY_FLOAT *expected, const UNITY_FLOAT *actual, const UNITY_UINT32 num_elements, const char *msg, const UNITY_UINT lineNumber, const UNITY_FLAGS_T flags)
void UnityAssertFloatsWithin (const UNITY_FLOAT delta, const UNITY_FLOAT expected, const UNITY_FLOAT actual, const char *msg, const UNITY_UINT lineNumber)
void UnityAssertFloatSpecial (const UNITY_FLOAT actual, const char *msg, const UNITY_UINT lineNumber, const UNITY_FLOAT_TRAIT_T style)
void UnityAssertNumbersWithin (const UNITY_UINT delta, const UNITY_INT expected, const UNITY_INT actual, const char *msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style)
void UnityAssertNumbersArrayWithin (const UNITY_UINT delta, const void *expected, const void *actual, const UNITY_UINT32 num_elements, const char *msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style, const UNITY_FLAGS_T flags)
void UnityAssertEqualString (const char *expected, const char *actual, const char *msg, const UNITY_UINT lineNumber)
void UnityAssertEqualStringLen (const char *expected, const char *actual, const UNITY_UINT32 length, const char *msg, const UNITY_UINT lineNumber)
void UnityAssertEqualStringArray (const void *expected, const char **actual, const UNITY_UINT32 num_elements, const char *msg, const UNITY_UINT lineNumber, const UNITY_FLAGS_T flags)
void UnityAssertEqualMemory (const void *expected, const void *actual, const UNITY_UINT32 length, const UNITY_UINT32 num_elements, const char *msg, const UNITY_UINT lineNumber, const UNITY_FLAGS_T flags)
const void * UnityNumToPtr (const UNITY_INT num, const UNITY_UINT8 size)
const void * UnityFloatToPtr (const float num)
void UnityFail (const char *msg, const UNITY_UINT line)
void UnityIgnore (const char *msg, const UNITY_UINT line)
void UnityMessage (const char *msg, const UNITY_UINT line)
void UnityDefaultTestRun (UnityTestFunction Func, const char *FuncName, const int FuncLineNum)
void UnitySetTestFile (const char *filename)
void UnityBegin (const char *filename)
int UnityEnd (void)
Variables
struct UNITY_STORAGE_T Unity
const char UnityStrOk [] = "OK"
const char UnityStrPass [] = "PASS"
const char UnityStrFail [] = "FAIL"
const char UnityStrIgnore [] = "IGNORE"
static const char UnityStrNull [] = "NULL"
static const char UnityStrSpacer [] = ". "
static const char UnityStrExpected [] = " Expected "
static const char UnityStrWas [] = " Was "
static const char UnityStrGt [] = " to be greater than "
static const char UnityStrLt [] = " to be less than "
static const char UnityStrOrEqual [] = "or equal to "
static const char UnityStrNotEqual [] = " to be not equal to "
static const char UnityStrElement [] = " Element "
static const char UnityStrByte [] = " Byte "
static const char UnityStrMemory [] = " Memory Mismatch."
static const char UnityStrDelta [] = " Values Not Within Delta "
static const char UnityStrPointless [] = " You Asked Me To Compare Nothing, Which Was Pointless."
static const char UnityStrNullPointerForExpected [] = " Expected pointer to be NULL"
static const char UnityStrNullPointerForActual [] = " Actual pointer was NULL"
static const char UnityStrNot [] = "Not "
static const char UnityStrInf [] = "Infinity"
static const char UnityStrNegInf [] = "Negative Infinity"
static const char UnityStrNaN [] = "NaN"
static const char UnityStrDet [] = "Determinate"
static const char UnityStrInvalidFloatTrait [] = "Invalid Float Trait"
const char UnityStrErrShorthand [] = "Unity Shorthand Support Disabled"
const char UnityStrErrFloat [] = "Unity Floating Point Disabled"
const char UnityStrErrDouble [] = "Unity Double Precision Disabled"
const char UnityStrErr64 [] = "Unity 64-bit Support Disabled"
static const char UnityStrBreaker [] = "-----------------------"
static const char UnityStrResultsTests [] = " Tests "
static const char UnityStrResultsFailures [] = " Failures "
static const char UnityStrResultsIgnored [] = " Ignored "
static const char UnityStrDetail1Name [] = "Function" " "
static const char UnityStrDetail2Name [] = " " "Argument" " "
union {
UNITY_INT8 i8
UNITY_INT16 i16
UNITY_INT32 i32
float f
} UnityQuickCompare
Macro Definition Documentation
PROGMEM
#define PROGMEM
Definition at line 13 of file unity.c.
RETURN_IF_FAIL_OR_IGNORE
#define RETURN_IF_FAIL_OR_IGNORE if (Unity.CurrentTestFailed || Unity.CurrentTestIgnored) TEST_ABORT()
Definition at line 24 of file unity.c.
Referenced by UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualString(), UnityAssertEqualStringArray(), UnityAssertEqualStringLen(), UnityAssertFloatSpecial(), UnityAssertFloatsWithin(), UnityAssertGreaterOrLessOrEqualNumber(), UnityAssertNumbersArrayWithin(), UnityAssertNumbersWithin(), UnityFail(), and UnityIgnore().
UNITY_FAIL_AND_BAIL
#define UNITY_FAIL_AND_BAIL { Unity.CurrentTestFailed = 1; UNITY_OUTPUT_FLUSH(); TEST_ABORT(); }
Definition at line 22 of file unity.c.
Referenced by UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualString(), UnityAssertEqualStringArray(), UnityAssertEqualStringLen(), UnityAssertFloatSpecial(), UnityAssertFloatsWithin(), UnityAssertGreaterOrLessOrEqualNumber(), UnityAssertNumbersArrayWithin(), UnityAssertNumbersWithin(), and UnityFail().
UNITY_FLOAT_OR_DOUBLE_WITHIN
#define UNITY_FLOAT_OR_DOUBLE_WITHIN (delta, expected, actual, diff)
Value:
    if (isinf(expected) && isinf(actual) && (((expected) < 0) == ((actual) < 0))) return 1;   \
    if (UNITY_NAN_CHECK) return 1;                                                            \
    (diff) = (actual) - (expected);                                                           \
    if ((diff) < 0) (diff) = -(diff);                                                         \
    if ((delta) < 0) (delta) = -(delta);                                                      \
    return !(isnan(diff) || isinf(diff) || ((diff) > (delta)))
Definition at line 871 of file unity.c.
Referenced by UnityFloatsWithin().
UNITY_IGNORE_AND_BAIL
#define UNITY_IGNORE_AND_BAIL { Unity.CurrentTestIgnored = 1; UNITY_OUTPUT_FLUSH(); TEST_ABORT(); }
Definition at line 23 of file unity.c.
Referenced by UnityIgnore().
UNITY_NAN_CHECK
#define UNITY_NAN_CHECK isnan(expected) && isnan(actual)
Definition at line 880 of file unity.c.
UNITY_PRINT_EXPECTED_AND_ACTUAL_FLOAT
#define UNITY_PRINT_EXPECTED_AND_ACTUAL_FLOAT (expected, actual)
Value:
  {                                                               \
    UnityPrint(UnityStrExpected);                                 \
    UnityPrintFloat(expected);                                    \
    UnityPrint(UnityStrWas);                                      \
    UnityPrintFloat(actual); }
Definition at line 886 of file unity.c.
Referenced by UnityAssertEqualFloatArray(), and UnityAssertFloatsWithin().
UnityPrintPointlessAndBail
#define UnityPrintPointlessAndBail ()
Value:
{                                          \
    UnityTestResultsFailBegin(lineNumber); \
    UnityPrint(UnityStrPointless);         \
    UnityAddMsgIfSpecified(msg);           \
    UNITY_FAIL_AND_BAIL; }
Definition at line 767 of file unity.c.
Referenced by UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualStringArray(), and UnityAssertNumbersArrayWithin().
Function Documentation
UnityAddMsgIfSpecified()
static void UnityAddMsgIfSpecified (const char * msg) static
Definition at line 565 of file unity.c.
References Unity, UnityPrint(), UnityStrDetail1Name, UnityStrDetail2Name, and UnityStrSpacer.
Referenced by UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualString(), UnityAssertEqualStringArray(), UnityAssertEqualStringLen(), UnityAssertFloatSpecial(), UnityAssertFloatsWithin(), UnityAssertGreaterOrLessOrEqualNumber(), UnityAssertNumbersArrayWithin(), UnityAssertNumbersWithin(), and UnityIsOneArrayNull().
UnityAssertBits()
void UnityAssertBits (const UNITY_INT mask, const UNITY_INT expected, const UNITY_INT actual, const char * msg, const UNITY_UINT lineNumber)
Definition at line 686 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, UNITY_FAIL_AND_BAIL, UNITY_LINE_TYPE, UnityAddMsgIfSpecified(), UnityPrint(), UnityPrintMask(), UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
UnityAssertEqualFloatArray()
void UnityAssertEqualFloatArray (const UNITY_FLOAT * expected, const UNITY_FLOAT * actual, const UNITY_UINT32 num_elements, const char * msg, const UNITY_UINT lineNumber, const UNITY_FLAGS_T flags)
Definition at line 905 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, UNITY_ARRAY_TO_ARRAY, UNITY_FAIL_AND_BAIL, UNITY_FLOAT_PRECISION, UNITY_INTERNAL_PTR, UNITY_LINE_TYPE, UNITY_PRINT_EXPECTED_AND_ACTUAL_FLOAT, UNITY_PTR_ATTRIBUTE, UnityAddMsgIfSpecified(), UnityFloatsWithin(), UnityIsOneArrayNull(), UnityPrint(), UnityPrintNumberUnsigned(), UnityPrintPointlessAndBail, UnityStrElement, and UnityTestResultsFailBegin().
UnityAssertEqualIntArray()
void UnityAssertEqualIntArray (const void * expected, const void * actual, const UNITY_UINT32 num_elements, const char * msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style, const UNITY_FLAGS_T flags)
Definition at line 775 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, UNITY_ARRAY_TO_ARRAY, UNITY_DISPLAY_RANGE_UINT, UNITY_FAIL_AND_BAIL, UNITY_INT_WIDTH, UNITY_INTERNAL_PTR, UNITY_LINE_TYPE, UNITY_PTR_ATTRIBUTE, UnityAddMsgIfSpecified(), UnityIsOneArrayNull(), UnityPrint(), UnityPrintNumberByStyle(), UnityPrintNumberUnsigned(), UnityPrintPointlessAndBail, UnityStrElement, UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
UnityAssertEqualMemory()
void UnityAssertEqualMemory (const void * expected, const void * actual, const UNITY_UINT32 length, const UNITY_UINT32 num_elements, const char * msg, const UNITY_UINT lineNumber, const UNITY_FLAGS_T flags)
Definition at line 1503 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, UNITY_ARRAY_TO_VAL, UNITY_DISPLAY_STYLE_HEX8, UNITY_FAIL_AND_BAIL, UNITY_INTERNAL_PTR, UNITY_LINE_TYPE, UNITY_PTR_ATTRIBUTE, UnityAddMsgIfSpecified(), UnityIsOneArrayNull(), UnityPrint(), UnityPrintNumberByStyle(), UnityPrintNumberUnsigned(), UnityPrintPointlessAndBail, UnityStrByte, UnityStrElement, UnityStrExpected, UnityStrMemory, UnityStrWas, and UnityTestResultsFailBegin().
UnityAssertEqualNumber()
void UnityAssertEqualNumber (const UNITY_INT expected, const UNITY_INT actual, const char * msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style)
Definition at line 707 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, UNITY_FAIL_AND_BAIL, UNITY_LINE_TYPE, UnityAddMsgIfSpecified(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
UnityAssertEqualString()
void UnityAssertEqualString (const char * expected, const char * actual, const char * msg, const UNITY_UINT lineNumber)
Definition at line 1345 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, Unity, UNITY_FAIL_AND_BAIL, UNITY_LINE_TYPE, UnityAddMsgIfSpecified(), UnityPrintExpectedAndActualStrings(), and UnityTestResultsFailBegin().
UnityAssertEqualStringArray()
void UnityAssertEqualStringArray (const void * expected, const char ** actual, const UNITY_UINT32 num_elements, const char * msg, const UNITY_UINT lineNumber, const UNITY_FLAGS_T flags)
Definition at line 1424 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, Unity, UNITY_ARRAY_TO_ARRAY, UNITY_FAIL_AND_BAIL, UNITY_INTERNAL_PTR, UNITY_LINE_TYPE, UnityAddMsgIfSpecified(), UnityIsOneArrayNull(), UnityPrint(), UnityPrintExpectedAndActualStrings(), UnityPrintNumberUnsigned(), UnityPrintPointlessAndBail, UnityStrElement, and UnityTestResultsFailBegin().
UnityAssertEqualStringLen()
void UnityAssertEqualStringLen (const char * expected, const char * actual, const UNITY_UINT32 length, const char * msg, const UNITY_UINT lineNumber)
Definition at line 1384 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, Unity, UNITY_FAIL_AND_BAIL, UNITY_LINE_TYPE, UnityAddMsgIfSpecified(), UnityPrintExpectedAndActualStringsLen(), and UnityTestResultsFailBegin().
UnityAssertFloatSpecial()
void UnityAssertFloatSpecial (const UNITY_FLOAT actual, const char * msg, const UNITY_UINT lineNumber, const UNITY_FLOAT_TRAIT_T style)
Definition at line 972 of file unity.c.
References isinf, isnan, RETURN_IF_FAIL_OR_IGNORE, UNITY_FAIL_AND_BAIL, UNITY_FLOAT_IS_DET, UNITY_FLOAT_IS_INF, UNITY_FLOAT_IS_NAN, UNITY_FLOAT_IS_NEG_INF, UNITY_FLOAT_IS_NOT_DET, UNITY_FLOAT_IS_NOT_INF, UNITY_FLOAT_IS_NOT_NAN, UNITY_FLOAT_IS_NOT_NEG_INF, UNITY_LINE_TYPE, UnityAddMsgIfSpecified(), UnityPrint(), UnityPrintFloat(), UnityStrDet, UnityStrExpected, UnityStrInf, UnityStrInvalidFloatTrait, UnityStrNaN, UnityStrNegInf, UnityStrNot, UnityStrWas, and UnityTestResultsFailBegin().
Referenced by testFloatTraitFailsOnInvalidTrait().
UnityAssertFloatsWithin()
void UnityAssertFloatsWithin (const UNITY_FLOAT delta, const UNITY_FLOAT expected, const UNITY_FLOAT actual, const char * msg, const UNITY_UINT lineNumber)
Definition at line 953 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, UNITY_FAIL_AND_BAIL, UNITY_LINE_TYPE, UNITY_PRINT_EXPECTED_AND_ACTUAL_FLOAT, UnityAddMsgIfSpecified(), UnityFloatsWithin(), and UnityTestResultsFailBegin().
UnityAssertGreaterOrLessOrEqualNumber()
void UnityAssertGreaterOrLessOrEqualNumber (const UNITY_INT threshold, const UNITY_INT actual, const UNITY_COMPARISON_T compare, const char * msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style)
Definition at line 728 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, UNITY_DISPLAY_RANGE_INT, UNITY_EQUAL_TO, UNITY_FAIL_AND_BAIL, UNITY_GREATER_THAN, UNITY_LINE_TYPE, UNITY_NOT_EQUAL, UNITY_SMALLER_THAN, UnityAddMsgIfSpecified(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrExpected, UnityStrGt, UnityStrLt, UnityStrNotEqual, UnityStrOrEqual, and UnityTestResultsFailBegin().
UnityAssertNumbersArrayWithin()
void UnityAssertNumbersArrayWithin (const UNITY_UINT delta, const void * expected, const void * actual, const UNITY_UINT32 num_elements, const char * msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style, const UNITY_FLAGS_T flags)
Definition at line 1225 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, Unity, UNITY_ARRAY_TO_ARRAY, UNITY_DISPLAY_RANGE_INT, UNITY_DISPLAY_RANGE_UINT, UNITY_FAIL_AND_BAIL, UNITY_INT_WIDTH, UNITY_INTERNAL_PTR, UNITY_LINE_TYPE, UNITY_PTR_ATTRIBUTE, UnityAddMsgIfSpecified(), UnityIsOneArrayNull(), UnityPrint(), UnityPrintNumberByStyle(), UnityPrintNumberUnsigned(), UnityPrintPointlessAndBail, UnityStrDelta, UnityStrElement, UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
UnityAssertNumbersWithin()
void UnityAssertNumbersWithin (const UNITY_UINT delta, const UNITY_INT expected, const UNITY_INT actual, const char * msg, const UNITY_UINT lineNumber, const UNITY_DISPLAY_STYLE_T style)
Definition at line 1178 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, Unity, UNITY_DISPLAY_RANGE_INT, UNITY_FAIL_AND_BAIL, UNITY_LINE_TYPE, UnityAddMsgIfSpecified(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrDelta, UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
UnityBegin()
void UnityBegin (const char * filename)
Definition at line 1855 of file unity.c.
References Unity, UNITY_CLR_DETAILS, and UNITY_OUTPUT_START.
Referenced by main(), and UnityMain().
UnityConcludeTest()
void UnityConcludeTest (void)
Definition at line 541 of file unity.c.
References Unity, UNITY_FLUSH_CALL, UNITY_PRINT_EOL, UNITY_PRINT_EXEC_TIME, UnityPrint(), UnityStrPass, and UnityTestResultsBegin().
Referenced by testFailureCountIncrementsAndIsReturnedAtEnd(), and UnityDefaultTestRun().
UnityDefaultTestRun()
void UnityDefaultTestRun (UnityTestFunction Func, const char * FuncName, const int FuncLineNum)
Definition at line 1827 of file unity.c.
References setUp(), tearDown(), TEST_PROTECT, Unity, UNITY_CLR_DETAILS, UNITY_EXEC_TIME_START, UNITY_EXEC_TIME_STOP, UNITY_LINE_TYPE, and UnityConcludeTest().
UnityEnd()
int UnityEnd (void)
Definition at line 1871 of file unity.c.
References Unity, UNITY_FLUSH_CALL, UNITY_OUTPUT_CHAR, UNITY_OUTPUT_COMPLETE, UNITY_PRINT_EOL, UnityPrint(), UnityPrintNumber(), UnityStrBreaker, UnityStrFail, UnityStrOk, UnityStrResultsFailures, UnityStrResultsIgnored, and UnityStrResultsTests.
Referenced by main(), testFailureCountIncrementsAndIsReturnedAtEnd(), and UnityMain().
UnityFail()
void UnityFail (const char * msg, const UNITY_UINT line)
Definition at line 1758 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, Unity, UNITY_FAIL_AND_BAIL, UNITY_LINE_TYPE, UNITY_OUTPUT_CHAR, UnityPrint(), UnityStrDetail1Name, UnityStrDetail2Name, UnityStrFail, UnityStrSpacer, and UnityTestResultsBegin().
UnityFloatsWithin()
static int UnityFloatsWithin (UNITY_FLOAT delta, UNITY_FLOAT expected, UNITY_FLOAT actual) static
Definition at line 898 of file unity.c.
References UNITY_FLOAT_OR_DOUBLE_WITHIN.
Referenced by UnityAssertEqualFloatArray(), and UnityAssertFloatsWithin().
UnityFloatToPtr()
const void * UnityFloatToPtr (const float num)
Definition at line 1610 of file unity.c.
References UNITY_INTERNAL_PTR, and UnityQuickCompare.
UnityIgnore()
void UnityIgnore (const char * msg, const UNITY_UINT line)
Definition at line 1795 of file unity.c.
References RETURN_IF_FAIL_OR_IGNORE, Unity, UNITY_IGNORE_AND_BAIL, UNITY_LINE_TYPE, UNITY_OUTPUT_CHAR, UnityPrint(), UnityStrIgnore, and UnityTestResultsBegin().
UnityIsOneArrayNull()
static int UnityIsOneArrayNull (const void * expected, const void * actual, const UNITY_UINT lineNumber, const char * msg) static
Definition at line 652 of file unity.c.
References UNITY_INTERNAL_PTR, UNITY_LINE_TYPE, UnityAddMsgIfSpecified(), UnityPrint(), UnityStrNullPointerForActual, UnityStrNullPointerForExpected, and UnityTestResultsFailBegin().
Referenced by UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualStringArray(), and UnityAssertNumbersArrayWithin().
UnityMessage()
void UnityMessage (const char * msg, const UNITY_UINT line)
Definition at line 1811 of file unity.c.
References Unity, UNITY_LINE_TYPE, UNITY_OUTPUT_CHAR, UNITY_PRINT_EOL, UnityPrint(), and UnityTestResultsBegin().
UnityNumToPtr()
const void * UnityNumToPtr (const UNITY_INT num, const UNITY_UINT8 size)
Definition at line 1584 of file unity.c.
References size, UNITY_INTERNAL_PTR, and UnityQuickCompare.
UnityPrint()
void UnityPrint (const char * string)
Definition at line 130 of file unity.c.
References UnityPrintChar().
Referenced by announceTestRun(), tearDown(), testCstringsEscapeSequence(), UnityAddMsgIfSpecified(), UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualStringArray(), UnityAssertFloatSpecial(), UnityAssertGreaterOrLessOrEqualNumber(), UnityAssertNumbersArrayWithin(), UnityAssertNumbersWithin(), UnityConcludeFixtureTest(), UnityConcludeTest(), UnityEnd(), UnityFail(), UnityGetCommandLineOptions(), UnityIgnore(), UnityIgnoreTest(), UnityIsOneArrayNull(), UnityMessage(), UnityPrintExpectedAndActualStrings(), UnityPrintExpectedAndActualStringsLen(), UnityPrintFloat(), UnityTestResultsBegin(), UnityTestResultsFailBegin(), and UnityTestRunner().
UnityPrintChar()
static void UnityPrintChar (const char * pch) static
Definition at line 80 of file unity.c.
References UNITY_OUTPUT_CHAR, and UnityPrintNumberHex().
Referenced by UnityPrint().
UnityPrintExpectedAndActualStrings()
static void UnityPrintExpectedAndActualStrings (const char * expected, const char * actual) static
Definition at line 592 of file unity.c.
References UNITY_OUTPUT_CHAR, UnityPrint(), UnityStrExpected, UnityStrNull, and UnityStrWas.
Referenced by UnityAssertEqualString(), and UnityAssertEqualStringArray().
UnityPrintExpectedAndActualStringsLen()
static void UnityPrintExpectedAndActualStringsLen (const char * expected, const char * actual, const UNITY_UINT32 length) static
Definition at line 619 of file unity.c.
References UNITY_OUTPUT_CHAR, UnityPrint(), UnityPrintLen(), UnityStrExpected, UnityStrNull, and UnityStrWas.
Referenced by UnityAssertEqualStringLen().
UnityPrintFloat()
void UnityPrintFloat (const UNITY_DOUBLE input_number)
Definition at line 336 of file unity.c.
References isinf, isnan, n, UNITY_OUTPUT_CHAR, and UnityPrint().
Referenced by UnityAssertFloatSpecial().
UnityPrintLen()
void UnityPrintLen (const char * string, const UNITY_UINT32 length)
Definition at line 152 of file unity.c.
References UNITY_OUTPUT_CHAR, and UnityPrintNumberHex().
Referenced by UnityPrintExpectedAndActualStringsLen().
UnityPrintMask()
void UnityPrintMask (const UNITY_UINT mask, const UNITY_UINT number)
Definition at line 301 of file unity.c.
References UNITY_INT_WIDTH, and UNITY_OUTPUT_CHAR.
Referenced by UnityAssertBits().
UnityPrintNumber()
void UnityPrintNumber (const UNITY_INT number_to_print)
Definition at line 241 of file unity.c.
References UNITY_OUTPUT_CHAR, and UnityPrintNumberUnsigned().
Referenced by UnityEnd(), UnityPrintNumberByStyle(), and UnityTestResultsBegin().
UnityPrintNumberByStyle()
void UnityPrintNumberByStyle (const UNITY_INT number, const UNITY_DISPLAY_STYLE_T style)
Definition at line 190 of file unity.c.
References UNITY_DISPLAY_RANGE_INT, UNITY_DISPLAY_RANGE_UINT, UNITY_DISPLAY_STYLE_CHAR, UNITY_OUTPUT_CHAR, UnityPrintNumber(), UnityPrintNumberHex(), and UnityPrintNumberUnsigned().
Referenced by UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertGreaterOrLessOrEqualNumber(), UnityAssertNumbersArrayWithin(), and UnityAssertNumbersWithin().
UnityPrintNumberHex()
void UnityPrintNumberHex (const UNITY_UINT number, const char nibbles_to_print)
Definition at line 275 of file unity.c.
References UNITY_MAX_NIBBLES, and UNITY_OUTPUT_CHAR.
Referenced by testHexPrintsUpToMaxNumberOfNibbles(), UnityPrintChar(), UnityPrintLen(), and UnityPrintNumberByStyle().
UnityPrintNumberUnsigned()
void UnityPrintNumberUnsigned (const UNITY_UINT number)
Definition at line 256 of file unity.c.
References UNITY_OUTPUT_CHAR.
Referenced by announceTestRun(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualStringArray(), UnityAssertNumbersArrayWithin(), UnityPrintNumber(), and UnityPrintNumberByStyle().
UnitySetTestFile()
void UnitySetTestFile (const char * filename)
Definition at line 1849 of file unity.c.
References Unity.
UnityTestResultsBegin()
static void UnityTestResultsBegin (const char * file, const UNITY_UINT line) static
Definition at line 490 of file unity.c.
References Unity, UNITY_LINE_TYPE, UNITY_OUTPUT_CHAR, UnityPrint(), and UnityPrintNumber().
Referenced by UnityConcludeTest(), UnityFail(), UnityIgnore(), UnityMessage(), and UnityTestResultsFailBegin().
UnityTestResultsFailBegin()
static void UnityTestResultsFailBegin (const UNITY_UINT line) static
Definition at line 533 of file unity.c.
References Unity, UNITY_LINE_TYPE, UNITY_OUTPUT_CHAR, UnityPrint(), UnityStrFail, and UnityTestResultsBegin().
Referenced by UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualString(), UnityAssertEqualStringArray(), UnityAssertEqualStringLen(), UnityAssertFloatSpecial(), UnityAssertFloatsWithin(), UnityAssertGreaterOrLessOrEqualNumber(), UnityAssertNumbersArrayWithin(), UnityAssertNumbersWithin(), and UnityIsOneArrayNull().
Variable Documentation
f
float f
Definition at line 1577 of file unity.c.
Referenced by ft_striteri(), and ft_strmapi().
i16
UNITY_INT16 i16
Definition at line 1571 of file unity.c.
i32
UNITY_INT32 i32
Definition at line 1572 of file unity.c.
i8
UNITY_INT8 i8
Definition at line 1570 of file unity.c.
Unity
struct UNITY_STORAGE_T Unity
Definition at line 26 of file unity.c.
Referenced by tearDown(), TEST(), TEST(), test_BufferGuardWriteFoundDuringFree(), test_BufferGuardWriteFoundDuringRealloc(), test_BufferOverrunFoundDuringFree(), test_BufferOverrunFoundDuringRealloc(), test_DetectsLeak(), test_ShouldCallMockInitAndVerifyFunctionsForEachTest(), testFailureCountIncrementsAndIsReturnedAtEnd(), testPreviousPass(), testProtection(), testUnitySizeInitializationReminder(), unity_free(), unity_realloc(), UnityAddMsgIfSpecified(), UnityAssertEqualString(), UnityAssertEqualStringArray(), UnityAssertEqualStringLen(), UnityAssertNumbersArrayWithin(), UnityAssertNumbersWithin(), UnityBegin(), UnityConcludeFixtureTest(), UnityConcludeTest(), UnityDefaultTestRun(), UnityEnd(), UnityFail(), UnityIgnore(), UnityIgnoreTest(), UnityMain(), UnityMalloc_EndTest(), UnityMessage(), UnitySetTestFile(), UnityTestResultsBegin(), UnityTestResultsFailBegin(), and UnityTestRunner().
[union]
union { ... } UnityQuickCompare
Referenced by UnityFloatToPtr(), and UnityNumToPtr().
UnityStrBreaker
const char UnityStrBreaker[] = "-----------------------" static
Definition at line 66 of file unity.c.
Referenced by UnityEnd().
UnityStrByte
const char UnityStrByte[] = " Byte " static
Definition at line 48 of file unity.c.
Referenced by UnityAssertEqualMemory().
UnityStrDelta
const char UnityStrDelta[] = " Values Not Within Delta " static
Definition at line 50 of file unity.c.
Referenced by UnityAssertNumbersArrayWithin(), and UnityAssertNumbersWithin().
UnityStrDet
const char UnityStrDet[] = "Determinate" static
Definition at line 59 of file unity.c.
Referenced by UnityAssertFloatSpecial().
UnityStrDetail1Name
const char UnityStrDetail1Name[] = "Function" " " static
Definition at line 71 of file unity.c.
Referenced by UnityAddMsgIfSpecified(), and UnityFail().
UnityStrDetail2Name
const char UnityStrDetail2Name[] = " " "Argument" " " static
Definition at line 72 of file unity.c.
Referenced by UnityAddMsgIfSpecified(), and UnityFail().
UnityStrElement
const char UnityStrElement[] = " Element " static
Definition at line 47 of file unity.c.
Referenced by UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualStringArray(), and UnityAssertNumbersArrayWithin().
UnityStrErr64
const char UnityStrErr64[] = "Unity 64-bit Support Disabled"
Definition at line 65 of file unity.c.
UnityStrErrDouble
const char UnityStrErrDouble[] = "Unity Double Precision Disabled"
Definition at line 64 of file unity.c.
UnityStrErrFloat
const char UnityStrErrFloat[] = "Unity Floating Point Disabled"
Definition at line 63 of file unity.c.
UnityStrErrShorthand
const char UnityStrErrShorthand[] = "Unity Shorthand Support Disabled"
Definition at line 62 of file unity.c.
UnityStrExpected
const char UnityStrExpected[] = " Expected " static
Definition at line 41 of file unity.c.
Referenced by UnityAssertBits(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertFloatSpecial(), UnityAssertGreaterOrLessOrEqualNumber(), UnityAssertNumbersArrayWithin(), UnityAssertNumbersWithin(), UnityPrintExpectedAndActualStrings(), and UnityPrintExpectedAndActualStringsLen().
UnityStrFail
const char UnityStrFail[] = "FAIL"
Definition at line 36 of file unity.c.
Referenced by UnityEnd(), UnityFail(), and UnityTestResultsFailBegin().
UnityStrGt
const char UnityStrGt[] = " to be greater than " static
Definition at line 43 of file unity.c.
Referenced by UnityAssertGreaterOrLessOrEqualNumber().
UnityStrIgnore
const char UnityStrIgnore[] = "IGNORE"
Definition at line 37 of file unity.c.
Referenced by UnityIgnore().
UnityStrInf
const char UnityStrInf[] = "Infinity" static
Definition at line 56 of file unity.c.
Referenced by UnityAssertFloatSpecial().
UnityStrInvalidFloatTrait
const char UnityStrInvalidFloatTrait[] = "Invalid Float Trait" static
Definition at line 60 of file unity.c.
Referenced by UnityAssertFloatSpecial().
UnityStrLt
const char UnityStrLt[] = " to be less than " static
Definition at line 44 of file unity.c.
Referenced by UnityAssertGreaterOrLessOrEqualNumber().
UnityStrMemory
const char UnityStrMemory[] = " Memory Mismatch." static
Definition at line 49 of file unity.c.
Referenced by UnityAssertEqualMemory().
UnityStrNaN
const char UnityStrNaN[] = "NaN" static
Definition at line 58 of file unity.c.
Referenced by UnityAssertFloatSpecial().
UnityStrNegInf
const char UnityStrNegInf[] = "Negative Infinity" static
Definition at line 57 of file unity.c.
Referenced by UnityAssertFloatSpecial().
UnityStrNot
const char UnityStrNot[] = "Not " static
Definition at line 55 of file unity.c.
Referenced by UnityAssertFloatSpecial().
UnityStrNotEqual
const char UnityStrNotEqual[] = " to be not equal to " static
Definition at line 46 of file unity.c.
Referenced by UnityAssertGreaterOrLessOrEqualNumber().
UnityStrNull
const char UnityStrNull[] = "NULL" static
Definition at line 39 of file unity.c.
Referenced by UnityPrintExpectedAndActualStrings(), and UnityPrintExpectedAndActualStringsLen().
UnityStrNullPointerForActual
const char UnityStrNullPointerForActual[] = " Actual pointer was NULL" static
Definition at line 53 of file unity.c.
Referenced by UnityIsOneArrayNull().
UnityStrNullPointerForExpected
const char UnityStrNullPointerForExpected[] = " Expected pointer to be NULL" static
Definition at line 52 of file unity.c.
Referenced by UnityIsOneArrayNull().
UnityStrOk
const char UnityStrOk[] = "OK"
Definition at line 34 of file unity.c.
Referenced by UnityEnd().
UnityStrOrEqual
const char UnityStrOrEqual[] = "or equal to " static
Definition at line 45 of file unity.c.
Referenced by UnityAssertGreaterOrLessOrEqualNumber().
UnityStrPass
const char UnityStrPass[] = "PASS"
Definition at line 35 of file unity.c.
Referenced by UnityConcludeFixtureTest(), and UnityConcludeTest().
UnityStrPointless
const char UnityStrPointless[] = " You Asked Me To Compare Nothing, Which Was Pointless." static
Definition at line 51 of file unity.c.
UnityStrResultsFailures
const char UnityStrResultsFailures[] = " Failures " static
Definition at line 68 of file unity.c.
Referenced by UnityEnd().
UnityStrResultsIgnored
const char UnityStrResultsIgnored[] = " Ignored " static
Definition at line 69 of file unity.c.
Referenced by UnityEnd().
UnityStrResultsTests
const char UnityStrResultsTests[] = " Tests " static
Definition at line 67 of file unity.c.
Referenced by UnityEnd().
UnityStrSpacer
const char UnityStrSpacer[] = ". " static
Definition at line 40 of file unity.c.
Referenced by UnityAddMsgIfSpecified(), and UnityFail().
UnityStrWas
const char UnityStrWas[] = " Was " static
Definition at line 42 of file unity.c.
Referenced by UnityAssertBits(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertFloatSpecial(), UnityAssertNumbersArrayWithin(), UnityAssertNumbersWithin(), UnityPrintExpectedAndActualStrings(), and UnityPrintExpectedAndActualStringsLen().