libft Tests: test_libft.c File Reference
test_libft.c File Reference
#include "unity/src/unity.h"
#include "libft.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <time.h>
#include <sys/time.h>
Functions
void setUp (void)
void tearDown (void)
void check_memory_leaks (void)
double measure_time (void(*test_func)(void))
int create_temp_file (const char *content)
void report_error (const char *test_name, const char *expected, const char *actual)
void test_isalpha (void)
void test_isdigit (void)
void test_isalnum (void)
void test_isascii (void)
void test_isprint (void)
void test_strlen (void)
void test_memset (void)
void test_bzero (void)
void test_memcpy (void)
void test_memmove (void)
void test_strlcpy (void)
void test_strlcat (void)
void test_toupper (void)
void test_tolower (void)
void test_strchr (void)
void test_strrchr (void)
void test_strncmp (void)
void test_memchr (void)
void test_memcmp (void)
void test_strnstr (void)
void test_atoi (void)
void test_calloc (void)
void test_strdup (void)
void test_substr (void)
void test_strjoin (void)
void test_strtrim (void)
void test_split (void)
void test_itoa (void)
char test_map (unsigned int i, char c)
void test_strmapi (void)
static void test_func (unsigned int i, char *c)
void test_striteri (void)
void test_putchar_fd (void)
void test_putstr_fd (void)
void test_putendl_fd (void)
void test_putnbr_fd (void)
void run_performance_test (const char *test_name, void(*test_func)(void))
int main (void)
Function Documentation
check_memory_leaks()
void check_memory_leaks (void)
Definition at line 16 of file test_libft.c.
Referenced by main().
create_temp_file()
int create_temp_file (const char * content)
Definition at line 74 of file test_libft.c.
main()
int main (void)
Definition at line 603 of file test_libft.c.
References check_memory_leaks(), run_performance_test(), RUN_TEST, test_atoi(), test_bzero(), test_calloc(), test_isalnum(), test_isalpha(), test_isascii(), test_isdigit(), test_isprint(), test_itoa(), test_memchr(), test_memcmp(), test_memcpy(), test_memmove(), test_memset(), test_putchar_fd(), test_putendl_fd(), test_putnbr_fd(), test_putstr_fd(), test_split(), test_strchr(), test_strdup(), test_striteri(), test_strjoin(), test_strlcat(), test_strlcpy(), test_strlen(), test_strmapi(), test_strncmp(), test_strnstr(), test_strrchr(), test_strtrim(), test_substr(), test_tolower(), test_toupper(), UNITY_BEGIN, and UNITY_END.
measure_time()
double measure_time (void(* test_func)(void))
Definition at line 65 of file test_libft.c.
References end, and test_func().
Referenced by run_performance_test().
report_error()
void report_error (const char * test_name, const char * expected, const char * actual)
Definition at line 84 of file test_libft.c.
run_performance_test()
void run_performance_test (const char * test_name, void(* test_func)(void))
Definition at line 594 of file test_libft.c.
References measure_time(), and test_func().
Referenced by main().
setUp()
void setUp (void)
Definition at line 12 of file test_libft.c.
Referenced by UnityDefaultTestRun().
tearDown()
void tearDown (void)
Definition at line 13 of file test_libft.c.
Referenced by UnityDefaultTestRun().
test_atoi()
void test_atoi (void)
Definition at line 288 of file test_libft.c.
References ft_atoi(), and TEST_ASSERT_EQUAL.
Referenced by main().
test_bzero()
void test_bzero (void)
Definition at line 165 of file test_libft.c.
References ft_bzero(), TEST_ASSERT_EQUAL, and TEST_ASSERT_EQUAL_STRING.
Referenced by main().
test_calloc()
void test_calloc (void)
Definition at line 299 of file test_libft.c.
References free, ft_calloc(), TEST_ASSERT_EQUAL, TEST_ASSERT_NOT_NULL, and TEST_ASSERT_NULL.
Referenced by main().
test_func()
static void test_func (unsigned int i, char * c) static
Definition at line 515 of file test_libft.c.
References c.
Referenced by measure_time(), run_performance_test(), and test_striteri().
test_isalnum()
void test_isalnum (void)
Definition at line 111 of file test_libft.c.
References ft_isalnum(), and TEST_ASSERT_EQUAL.
Referenced by main().
test_isalpha()
void test_isalpha (void)
Definition at line 91 of file test_libft.c.
References ft_isalpha(), and TEST_ASSERT_EQUAL.
Referenced by main().
test_isascii()
void test_isascii (void)
Definition at line 121 of file test_libft.c.
References ft_isascii(), and TEST_ASSERT_EQUAL.
Referenced by main().
test_isdigit()
void test_isdigit (void)
Definition at line 101 of file test_libft.c.
References ft_isdigit(), and TEST_ASSERT_EQUAL.
Referenced by main().
test_isprint()
void test_isprint (void)
Definition at line 128 of file test_libft.c.
References ft_isprint(), and TEST_ASSERT_EQUAL.
Referenced by main().
test_itoa()
void test_itoa (void)
Definition at line 475 of file test_libft.c.
References free, ft_itoa(), and TEST_ASSERT_EQUAL_STRING.
Referenced by main().
test_map()
char test_map (unsigned int i, char c)
Definition at line 497 of file test_libft.c.
References c.
Referenced by test_strmapi().
test_memchr()
void test_memchr (void)
Definition at line 264 of file test_libft.c.
References ft_memchr(), TEST_ASSERT_EQUAL_STRING, and TEST_ASSERT_NULL.
Referenced by main().
test_memcmp()
void test_memcmp (void)
Definition at line 272 of file test_libft.c.
References ft_memcmp(), TEST_ASSERT, and TEST_ASSERT_EQUAL.
Referenced by main().
test_memcpy()
void test_memcpy (void)
Definition at line 177 of file test_libft.c.
References ft_memcpy(), TEST_ASSERT_EQUAL_PTR, and TEST_ASSERT_EQUAL_STRING.
Referenced by main().
test_memmove()
void test_memmove (void)
Definition at line 190 of file test_libft.c.
References ft_memmove(), TEST_ASSERT_EQUAL_PTR, and TEST_ASSERT_EQUAL_STRING.
Referenced by main().
test_memset()
void test_memset (void)
Definition at line 153 of file test_libft.c.
References ft_memset(), TEST_ASSERT_EQUAL_PTR, and TEST_ASSERT_EQUAL_STRING.
Referenced by main().
test_putchar_fd()
void test_putchar_fd (void)
Definition at line 525 of file test_libft.c.
References c, ft_putchar_fd(), TEST_ASSERT_EQUAL, and TEST_ASSERT_NOT_EQUAL.
Referenced by main().
test_putendl_fd()
void test_putendl_fd (void)
Definition at line 559 of file test_libft.c.
References ft_putendl_fd(), TEST_ASSERT_EQUAL, TEST_ASSERT_EQUAL_STRING, and TEST_ASSERT_NOT_EQUAL.
Referenced by main().
test_putnbr_fd()
void test_putnbr_fd (void)
Definition at line 576 of file test_libft.c.
References ft_putnbr_fd(), TEST_ASSERT_EQUAL, TEST_ASSERT_EQUAL_STRING, and TEST_ASSERT_NOT_EQUAL.
Referenced by main().
test_putstr_fd()
void test_putstr_fd (void)
Definition at line 542 of file test_libft.c.
References ft_putstr_fd(), TEST_ASSERT_EQUAL, TEST_ASSERT_EQUAL_STRING, and TEST_ASSERT_NOT_EQUAL.
Referenced by main().
test_split()
void test_split (void)
Definition at line 416 of file test_libft.c.
References free, ft_split(), TEST_ASSERT_EQUAL_STRING, TEST_ASSERT_NOT_NULL, and TEST_ASSERT_NULL.
Referenced by main().
test_strchr()
void test_strchr (void)
Definition at line 240 of file test_libft.c.
References ft_strchr(), TEST_ASSERT_EQUAL_STRING, and TEST_ASSERT_NULL.
Referenced by main().
test_strdup()
void test_strdup (void)
Definition at line 321 of file test_libft.c.
References free, ft_strdup(), TEST_ASSERT_EQUAL_STRING, TEST_ASSERT_NOT_NULL, and TEST_ASSERT_NULL.
Referenced by main().
test_striteri()
void test_striteri (void)
Definition at line 519 of file test_libft.c.
References ft_striteri(), TEST_ASSERT_EQUAL_STRING, and test_func().
Referenced by main().
test_strjoin()
void test_strjoin (void)
Definition at line 382 of file test_libft.c.
References free, ft_strjoin(), TEST_ASSERT_EQUAL_STRING, and TEST_ASSERT_NULL.
Referenced by main().
test_strlcat()
void test_strlcat (void)
Definition at line 213 of file test_libft.c.
References ft_strlcat(), TEST_ASSERT_EQUAL, and TEST_ASSERT_EQUAL_STRING.
Referenced by main().
test_strlcpy()
void test_strlcpy (void)
Definition at line 202 of file test_libft.c.
References ft_strlcpy(), TEST_ASSERT_EQUAL, and TEST_ASSERT_EQUAL_STRING.
Referenced by main().
test_strlen()
void test_strlen (void)
Definition at line 137 of file test_libft.c.
References ft_strlen(), and TEST_ASSERT_EQUAL.
Referenced by main().
test_strmapi()
void test_strmapi (void)
Definition at line 502 of file test_libft.c.
References free, ft_strmapi(), TEST_ASSERT_EQUAL_STRING, and test_map().
Referenced by main().
test_strncmp()
void test_strncmp (void)
Definition at line 256 of file test_libft.c.
References ft_strncmp(), TEST_ASSERT, and TEST_ASSERT_EQUAL.
Referenced by main().
test_strnstr()
void test_strnstr (void)
Definition at line 280 of file test_libft.c.
References ft_strnstr(), TEST_ASSERT_EQUAL_STRING, and TEST_ASSERT_NULL.
Referenced by main().
test_strrchr()
void test_strrchr (void)
Definition at line 248 of file test_libft.c.
References ft_strrchr(), TEST_ASSERT_EQUAL_STRING, and TEST_ASSERT_NULL.
Referenced by main().
test_strtrim()
void test_strtrim (void)
Definition at line 399 of file test_libft.c.
References free, ft_strtrim(), TEST_ASSERT_EQUAL_STRING, and TEST_ASSERT_NULL.
Referenced by main().
test_substr()
void test_substr (void)
Definition at line 362 of file test_libft.c.
References free, ft_substr(), TEST_ASSERT_EQUAL_STRING, and TEST_ASSERT_NULL.
Referenced by main().
test_tolower()
void test_tolower (void)
Definition at line 232 of file test_libft.c.
References ft_tolower(), and TEST_ASSERT_EQUAL.
Referenced by main().
test_toupper()
void test_toupper (void)
Definition at line 224 of file test_libft.c.
References ft_toupper(), and TEST_ASSERT_EQUAL.
Referenced by main().