libft Tests: unity/extras/fixture/src/unity_fixture.c File Reference
unity_fixture.c File Reference
#include "unity_fixture.h"
#include "unity_internals.h"
#include <string.h>
Classes
struct PointerPair
Functions
void setUp (void)
void tearDown (void)
static void announceTestRun (unsigned int runNumber)
int UnityMain (int argc, const char *argv[], void(*runAllTests)(void))
static int selected (const char *filter, const char *select, const char *name)
static int testSelected (const char *test)
static int groupSelected (const char *group)
void UnityTestRunner (unityfunction *setup, unityfunction *testBody, unityfunction *teardown, const char *printableName, const char *group, const char *name, const char *file, unsigned int line)
void UnityIgnoreTest (const char *printableName, const char *group, const char *name)
void UnityPointer_Init (void)
void UnityPointer_Set (void **pointer, void *newValue, UNITY_LINE_TYPE line)
void UnityPointer_UndoAllSets (void)
int UnityGetCommandLineOptions (int argc, const char *argv[])
void UnityConcludeFixtureTest (void)
Variables
struct UNITY_FIXTURE_T UnityFixture
static struct PointerPair pointer_store [5]
static int pointer_index = 0
Function Documentation
announceTestRun()
static void announceTestRun (unsigned int runNumber) static
Definition at line 21 of file unity_fixture.c.
References UNITY_PRINT_EOL, UnityFixture, UnityPrint(), and UnityPrintNumberUnsigned().
Referenced by UnityMain().
groupSelected()
static int groupSelected (const char * group) static
Definition at line 65 of file unity_fixture.c.
References group, selected(), and UnityFixture.
Referenced by UnityIgnoreTest(), and UnityTestRunner().
selected()
static int selected (const char * filter, const char * select, const char * name) static
Definition at line 49 of file unity_fixture.c.
References name.
Referenced by groupSelected(), and testSelected().
setUp()
void setUp (void)
Definition at line 18 of file unity_fixture.c.
tearDown()
void tearDown (void)
Definition at line 19 of file unity_fixture.c.
testSelected()
static int testSelected (const char * test) static
Definition at line 60 of file unity_fixture.c.
References selected(), and UnityFixture.
Referenced by UnityIgnoreTest(), and UnityTestRunner().
UnityConcludeFixtureTest()
void UnityConcludeFixtureTest (void)
Definition at line 321 of file unity_fixture.c.
References Unity, UNITY_EXEC_TIME_STOP, UNITY_PRINT_EOL, UNITY_PRINT_EXEC_TIME, UnityFixture, UnityPrint(), and UnityStrPass.
Referenced by TEST(), and UnityTestRunner().
UnityGetCommandLineOptions()
int UnityGetCommandLineOptions (int argc, const char * argv[])
Definition at line 188 of file unity_fixture.c.
References UNITY_PRINT_EOL, UnityFixture, and UnityPrint().
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and UnityMain().
UnityIgnoreTest()
void UnityIgnoreTest (const char * printableName, const char * group, const char * name)
Definition at line 125 of file unity_fixture.c.
References group, groupSelected(), name, testSelected(), Unity, UNITY_OUTPUT_CHAR, UNITY_PRINT_EOL, UnityFixture, and UnityPrint().
Referenced by TEST().
UnityMain()
int UnityMain (int argc, const char * argv[], void(* runAllTests)(void))
Definition at line 30 of file unity_fixture.c.
References announceTestRun(), runAllTests(), Unity, UNITY_PRINT_EOL, UnityBegin(), UnityEnd(), UnityFixture, and UnityGetCommandLineOptions().
Referenced by main(), and TEST().
UnityPointer_Init()
void UnityPointer_Init (void)
Definition at line 158 of file unity_fixture.c.
References pointer_index.
Referenced by TEST(), and UnityTestRunner().
UnityPointer_Set()
void UnityPointer_Set (void ** pointer, void * newValue, UNITY_LINE_TYPE line)
Definition at line 163 of file unity_fixture.c.
References PointerPair::pointer, pointer_index, pointer_store, UNITY_LINE_TYPE, UNITY_MAX_POINTERS, and UNITY_TEST_FAIL.
UnityPointer_UndoAllSets()
void UnityPointer_UndoAllSets (void)
Definition at line 178 of file unity_fixture.c.
References PointerPair::old_value, pointer_index, and pointer_store.
Referenced by TEST(), TEST(), and UnityTestRunner().
UnityTestRunner()
void UnityTestRunner (unityfunction * setup, unityfunction * testBody, unityfunction * teardown, const char * printableName, const char * group, const char * name, const char * file, unsigned int line)
Definition at line 70 of file unity_fixture.c.
References group, groupSelected(), name, TEST_PROTECT, testSelected(), Unity, UNITY_EXEC_TIME_START, UNITY_OUTPUT_CHAR, UnityConcludeFixtureTest(), UnityFixture, UnityPointer_Init(), UnityPointer_UndoAllSets(), and UnityPrint().
Variable Documentation
pointer_index
int pointer_index = 0 static
Definition at line 156 of file unity_fixture.c.
Referenced by UnityPointer_Init(), UnityPointer_Set(), and UnityPointer_UndoAllSets().
pointer_store
struct PointerPair pointer_store[5] static
Definition at line 155 of file unity_fixture.c.
Referenced by UnityPointer_Set(), and UnityPointer_UndoAllSets().
UnityFixture
struct UNITY_FIXTURE_T UnityFixture
Definition at line 12 of file unity_fixture.c.
Referenced by announceTestRun(), groupSelected(), runAllTests(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_GROUP(), TEST_GROUP_RUNNER(), TEST_SETUP(), TEST_SETUP(), TEST_TEAR_DOWN(), TEST_TEAR_DOWN(), testSelected(), UnityConcludeFixtureTest(), UnityGetCommandLineOptions(), UnityIgnoreTest(), UnityMain(), and UnityTestRunner().