libft Tests: unity/examples/example_4/test/test_runners/TestProductionCode_Runner.c File Reference
TestProductionCode_Runner.c File Reference
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "ProductionCode.h"
Macros
#define RUN_TEST(TestFunc, TestLineNum)
Functions
void setUp (void)
void tearDown (void)
void test_FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode (void)
void test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken (void)
void test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue (void)
void test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValueAgain (void)
void test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed (void)
void resetTest (void)
int main (void)
Macro Definition Documentation
RUN_TEST
#define RUN_TEST (TestFunc, TestLineNum)
Value:
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}
Definition at line 4 of file TestProductionCode_Runner.c.
Function Documentation
main()
int main (void)
Definition at line 47 of file TestProductionCode_Runner.c.
References RUN_TEST, test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken(), test_FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode(), test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed(), test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue(), test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValueAgain(), UnityBegin(), and UnityEnd().
resetTest()
void resetTest (void)
Definition at line 39 of file TestProductionCode_Runner.c.
References setUp(), and tearDown().
setUp()
void setUp (void) extern
Definition at line 12 of file test_libft.c.
tearDown()
void tearDown (void) extern
Definition at line 13 of file test_libft.c.
test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken()
void test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken (void) extern
Definition at line 36 of file TestProductionCode.c.
References FindFunction_WhichIsBroken(), and TEST_ASSERT_EQUAL.
test_FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode()
void test_FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode (void) extern
Definition at line 26 of file TestProductionCode.c.
References FindFunction_WhichIsBroken(), and TEST_ASSERT_EQUAL.
test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed()
void test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed (void) extern
Definition at line 63 of file TestProductionCode.c.
References FunctionWhichReturnsLocalVariable(), and TEST_ASSERT_EQUAL_HEX.
test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue()
void test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue (void) extern
Definition at line 47 of file TestProductionCode.c.
References Counter, FunctionWhichReturnsLocalVariable(), and TEST_ASSERT_EQUAL_HEX.
test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValueAgain()
void test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValueAgain (void) extern
Definition at line 57 of file TestProductionCode.c.
References FunctionWhichReturnsLocalVariable(), and TEST_ASSERT_EQUAL_HEX.