libft Tests: /Users/dinolu/Documents/42practice/Libft/ft_split.c File Reference
ft_split.c File Reference
#include "libft.h"
Functions
static size_t count_words (const char *s, char c)
static char * extract_word (const char *s, char c)
static int fill_array (char **array, const char *s, char c)
char ** ft_split (const char *s, char c)
Function Documentation
count_words()
static size_t count_words (const char * s, char c) static
Definition at line 15 of file ft_split.c.
References c, and count.
Referenced by ft_split().
extract_word()
static char * extract_word (const char * s, char c) static
Definition at line 38 of file ft_split.c.
References c, ft_memcpy(), and malloc.
Referenced by fill_array().
fill_array()
static int fill_array (char ** array, const char * s, char c) static
Definition at line 56 of file ft_split.c.
References c, extract_word(), and free.
Referenced by ft_split().
ft_split()
char ** ft_split (const char * s, char c)
Definition at line 83 of file ft_split.c.
References c, count_words(), fill_array(), and malloc.
Referenced by test_split().