libft Tests: unity/extras/memory/test/unity_output_Spy.c File Reference
unity_output_Spy.c File Reference
#include "unity.h"
#include "unity_output_Spy.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
Functions
void UnityOutputCharSpy_Create (int s)
void UnityOutputCharSpy_Destroy (void)
void UnityOutputCharSpy_OutputChar (int c)
const char * UnityOutputCharSpy_Get (void)
void UnityOutputCharSpy_Enable (int enable)
Variables
static int size
static int count
static char * buffer
static int spy_enable
Function Documentation
UnityOutputCharSpy_Create()
void UnityOutputCharSpy_Create (int s)
Definition at line 20 of file unity_output_Spy.c.
References buffer, count, malloc, size, spy_enable, and TEST_ASSERT_NOT_NULL_MESSAGE.
Referenced by setUp().
UnityOutputCharSpy_Destroy()
void UnityOutputCharSpy_Destroy (void)
Definition at line 30 of file unity_output_Spy.c.
References buffer, free, and size.
Referenced by tearDown().
UnityOutputCharSpy_Enable()
void UnityOutputCharSpy_Enable (int enable)
Definition at line 54 of file unity_output_Spy.c.
References spy_enable.
Referenced by test_BufferGuardWriteFoundDuringFree(), test_BufferGuardWriteFoundDuringRealloc(), test_BufferOverrunFoundDuringFree(), test_BufferOverrunFoundDuringRealloc(), and test_DetectsLeak().
UnityOutputCharSpy_Get()
const char * UnityOutputCharSpy_Get (void)
Definition at line 49 of file unity_output_Spy.c.
References buffer.
Referenced by test_BufferGuardWriteFoundDuringFree(), test_BufferGuardWriteFoundDuringRealloc(), test_BufferOverrunFoundDuringFree(), test_BufferOverrunFoundDuringRealloc(), and test_DetectsLeak().
UnityOutputCharSpy_OutputChar()
void UnityOutputCharSpy_OutputChar (int c)
Definition at line 36 of file unity_output_Spy.c.
References buffer, c, count, size, and spy_enable.
Variable Documentation
buffer
char* buffer static
Definition at line 17 of file unity_output_Spy.c.
Referenced by UnityOutputCharSpy_Create(), UnityOutputCharSpy_Destroy(), UnityOutputCharSpy_Get(), and UnityOutputCharSpy_OutputChar().
count
int count static
Definition at line 16 of file unity_output_Spy.c.
Referenced by count_digits(), count_words(), UnityOutputCharSpy_Create(), and UnityOutputCharSpy_OutputChar().
size
int size static
Definition at line 15 of file unity_output_Spy.c.
Referenced by ft_calloc(), ft_strlcat(), ft_strlcpy(), unity_calloc(), unity_malloc(), unity_realloc(), unity_size_round_up(), UnityNumToPtr(), UnityOutputCharSpy_Create(), UnityOutputCharSpy_Destroy(), and UnityOutputCharSpy_OutputChar().
spy_enable
int spy_enable static
Definition at line 18 of file unity_output_Spy.c.
Referenced by UnityOutputCharSpy_Create(), UnityOutputCharSpy_Enable(), and UnityOutputCharSpy_OutputChar().