name: Libft Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make valgrind
    
    - name: Build and test
      run: |
        make
        make test
    
    - name: Check for memory leaks (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt ./test_libft
        if grep -q "definitely lost: [1-9]" valgrind-out.txt; then
          echo "Memory leaks detected!"
          cat valgrind-out.txt
          exit 1
        fi
    
    - name: Check for memory leaks (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        leaks --atExit -- ./test_libft > leaks-out.txt 2>&1
        if grep -q "leaks for" leaks-out.txt; then
          echo "Memory leaks detected!"
          cat leaks-out.txt
          exit 1
        fi
    
    - name: Upload test results (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: test-results-ubuntu
        path: valgrind-out.txt
        if-no-files-found: warn

    - name: Upload test results (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: test-results-macos
        path: leaks-out.txt
        if-no-files-found: warn 