name: Libft Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Checkout Libft
      run: |
        git clone https://github.com/Dino-Lu/Libft.git ../Libft
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make valgrind
    
    - name: Build and test
      run: |
        make
        make test
    
    - name: Check for memory leaks
      run: |
        valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt ./test_libft
        if grep -q "definitely lost: [1-9]" valgrind-out.txt; then
          echo "Memory leaks detected!"
          cat valgrind-out.txt
          exit 1
        fi
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-ubuntu
        path: valgrind-out.txt
        if-no-files-found: warn

  macos-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Checkout Libft
      run: |
        git clone https://github.com/Dino-Lu/Libft.git ../Libft
    
    - name: Build and test
      run: |
        make
        make test
    
    - name: Check for memory leaks
      run: |
        leaks --atExit -- ./test_libft > leaks-out.txt 2>&1
        if grep -q "leaks for" leaks-out.txt; then
          echo "Memory leaks detected!"
          cat leaks-out.txt
          exit 1
        fi
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-macos
        path: leaks-out.txt
        if-no-files-found: warn 