libft Tests: unity/extras/memory/src/unity_memory.c File Reference
unity_memory.c File Reference
#include "unity.h"
#include "unity_memory.h"
#include <string.h>
#include <stdlib.h>
Classes
struct GuardBytes
Macros
#define MALLOC_DONT_FAIL -1
#define UNITY_MALLOC_ALIGNMENT (UNITY_POINTER_WIDTH / 8)
Typedefs
typedef struct GuardBytes Guard
Functions
void UnityMalloc_StartTest (void)
void UnityMalloc_EndTest (void)
void UnityMalloc_MakeMallocFailAfterCount (int countdown)
static size_t unity_size_round_up (size_t size)
void * unity_malloc (size_t size)
static int isOverrun (void *mem)
static void release_memory (void *mem)
void unity_free (void *mem)
void * unity_calloc (size_t num, size_t size)
void * unity_realloc (void *oldMem, size_t size)
Variables
static int malloc_count
static int malloc_fail_countdown = -1
static const char end [] = "END"
Macro Definition Documentation
MALLOC_DONT_FAIL
#define MALLOC_DONT_FAIL -1
Definition at line 12 of file unity_memory.c.
Referenced by unity_malloc(), UnityMalloc_EndTest(), and UnityMalloc_StartTest().
UNITY_MALLOC_ALIGNMENT
#define UNITY_MALLOC_ALIGNMENT (UNITY_POINTER_WIDTH / 8)
Definition at line 56 of file unity_memory.c.
Referenced by unity_size_round_up().
Typedef Documentation
Guard
typedef struct GuardBytes Guard
Function Documentation
isOverrun()
static int isOverrun (void * mem) static
Definition at line 108 of file unity_memory.c.
References end, GuardBytes::guard_space, and GuardBytes::size.
Referenced by unity_free(), and unity_realloc().
release_memory()
static void release_memory (void * mem) static
Definition at line 117 of file unity_memory.c.
References end, malloc_count, GuardBytes::size, UNITY_FREE, and unity_size_round_up().
Referenced by unity_free(), and unity_realloc().
unity_calloc()
void * unity_calloc (size_t num, size_t size)
Definition at line 156 of file unity_memory.c.
References size, and unity_malloc().
unity_free()
void unity_free (void * mem)
Definition at line 139 of file unity_memory.c.
References isOverrun(), release_memory(), Unity, and UNITY_TEST_FAIL.
unity_malloc()
void * unity_malloc (size_t size)
Definition at line 68 of file unity_memory.c.
References end, GuardBytes::guard_space, malloc_count, MALLOC_DONT_FAIL, malloc_fail_countdown, GuardBytes::size, size, UNITY_MALLOC, and unity_size_round_up().
Referenced by unity_calloc(), and unity_realloc().
unity_realloc()
void * unity_realloc (void * oldMem, size_t size)
Definition at line 164 of file unity_memory.c.
References end, isOverrun(), release_memory(), GuardBytes::size, size, Unity, unity_malloc(), unity_size_round_up(), and UNITY_TEST_FAIL.
unity_size_round_up()
static size_t unity_size_round_up (size_t size) static
Definition at line 59 of file unity_memory.c.
References size, and UNITY_MALLOC_ALIGNMENT.
Referenced by release_memory(), unity_malloc(), and unity_realloc().
UnityMalloc_EndTest()
void UnityMalloc_EndTest (void)
Definition at line 22 of file unity_memory.c.
References malloc_count, MALLOC_DONT_FAIL, malloc_fail_countdown, Unity, and UNITY_TEST_FAIL.
Referenced by tearDown(), and test_DetectsLeak().
UnityMalloc_MakeMallocFailAfterCount()
void UnityMalloc_MakeMallocFailAfterCount (int countdown)
Definition at line 31 of file unity_memory.c.
References malloc_fail_countdown.
Referenced by test_ForceMallocFail().
UnityMalloc_StartTest()
void UnityMalloc_StartTest (void)
Definition at line 16 of file unity_memory.c.
References malloc_count, MALLOC_DONT_FAIL, and malloc_fail_countdown.
Referenced by setUp().
Variable Documentation
end
const char end[] = "END" static
Definition at line 57 of file unity_memory.c.
Referenced by ft_strtrim(), isOverrun(), measure_time(), release_memory(), unity_malloc(), and unity_realloc().
malloc_count
int malloc_count static
Definition at line 13 of file unity_memory.c.
Referenced by release_memory(), unity_malloc(), UnityMalloc_EndTest(), and UnityMalloc_StartTest().
malloc_fail_countdown
int malloc_fail_countdown = -1 static
Definition at line 14 of file unity_memory.c.
Referenced by unity_malloc(), UnityMalloc_EndTest(), UnityMalloc_MakeMallocFailAfterCount(), and UnityMalloc_StartTest().